apiVersion: kubeflow.org/v1beta1
kind: TFJob
metadata:
  labels:
    ksonnet.io/component: train
  name: $(trainingName)
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Chief:
      replicas: 1
      template:
        spec:
          containers:
          - args:
            - --tf-model-dir=$(modelDir)
            - --tf-export-dir=$(exportDir)
            - --tf-train-steps=200
            - --tf-batch-size=100
            - --tf-learning-rate=0.01
            command:
            - /usr/bin/python
            - /opt/model.py
            env:
            - name: modelDir
              value: $(modelDir)
            - name: exportDir
              value: $(exportDir)        
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: $(GOOGLE_APPLICATION_CREDENTIALS)
            image: gcr.io/kubeflow-examples/mnist/model:v20190111-v0.2-148-g313770f
            name: tensorflow
            volumeMounts:
            - mountPath: $(secretMountPath)
              name: user-gcp-sa
              readOnly: true
            workingDir: /opt
          restartPolicy: OnFailure
          volumes:
          - name: user-gcp-sa
            secret:
              secretName: $(secretName)