apiVersion: v1
data:
  monitoring_config.txt: |-
    prometheus_config: {
      enable: true,
      path: "/monitoring/prometheus/metrics"
    }
kind: ConfigMap
metadata:
  labels:
    ksonnet.io/component: mnist-deploy-gcp
  name: mnist-deploy-gcp-config
  namespace: kubeflow